# Base config for ScanNet++ when using 3DGS renderer. Use via: inherit_from: configs/scannetpp/scannetpp_3dgs.yaml
inherit_from: configs/scannetpp/scannetpp.yaml
renderer: "3dgs"
mapping:
  use_normal_reg: false
  use_dist_reg: false
